language: scala
jdk:
- openjdk8
- oraclejdk8
scala:
- 2.11.7
cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.ivy2/cache'
before_script:
- sbt allDependencies
services:
- mongodb
env:
- MONGODB_URI=mongodb://localhost:27017/siz
notifications:
  slack:
    secure: Qy8LZF5jvJaFDovRomGZbs427VlZvlragAwLIi1340QwiCteYJJv9dQKOZ/iW+TinB6j7teaHsk3h2TJOC73G6BEJ9VSlfEbg+qxpLqh255hZl9rnDWQdm6kQMyqgxVzCCfxcWTjbvMg5rhLkPMmagHzR3zqJw13Yf2JpvLv+k4=
