mongo:
  image: mongo:2.6.10
  command: mongod --smallfiles
  ports:
   - "27017:27017"
api:
  build: .
  environment:
    MONGODB_URI: mongodb://mongo:27017/siz
  ports:
   - "9000:9000"
  command: sbt test
#  volumes:
#   - .:/var/www/siz-api
  links:
   - mongo

