# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Siz API
  description: Enjoy your favorite video content with Siz!
  version: "1.0.0"
# the domain of the service
# array of all schemes that your API supports
schemes:
  - http
  - https
# will be prefixed to all paths
#basePath: /v1
produces:
  - application/json
paths:
  /tokens:
    post:
      summary: Create a token
      description: Create a unique token.
      tags:
        - Token
        - Login
      parameters:
        - name: mandatory empty payload ( default is {} )
          in: body
          schema:
            $ref: '#/definitions/EmptyObject'
          
      responses:
        200:
          description: An object describing the token
          schema:
            $ref: '#/definitions/Token'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /stories:
    get:
      summary: Story endpoint
      description: Siz provides this api to look for a filtered list of stories, or fetch the whole lot of stories
      tags:
        - Search
      parameters:
        - name: slug
          in: query
          description: The slug, for example `my-favorite-story'
          type: string
      responses:
        200:
          description: The story
          schema:
            $ref: '#/definitions/Story'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  EmptyObject:
    properties:
      ignore_me:
        type: string #todo trouver un moyen de décrire l'objet vide {}
  Token:
    properties:
      id:
        type: string
      viewerProfileId:
        type: string
      userId:
        type: string
      storyIdToShow:
         type: string
  Story:
    properties:
      boxes:
        type: array
        properties:
          height:
            type: string
          width:
            type: string
          formats:
            type: string
            description: incomplete description at the moment. (TODO)
        type: string
      creationDate:
        type: string
      id:
        type: string
      slug:
        type: string
      title:
        type: string
  Error:
    properties:
      errors:
        properties:
          title:
            type: string